name: "Linting"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  pylint:
    name: Python Code Quality and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - group: linting
            commands: |
              uv run pylint sapsucker
              uv run pylint --recursive=y examples
          - group: type_check
            commands: |
              uv run mypy --show-error-codes src/sapsucker --strict
              uv run mypy --show-error-codes examples/sapsucker --strict --ignore-missing-imports
          - group: spell_check
            commands: |
              uv run codespell --ignore-words=domain-specific-terms.txt src
              uv run codespell --ignore-words=domain-specific-terms.txt examples
              uv run codespell --ignore-words=domain-specific-terms.txt README.md
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"
      - name: Install Dependencies
        run: uv sync --group ${{ matrix.group }}
      - name: Run ${{ matrix.group }}
        run: ${{ matrix.commands }}
